/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_melvincabatuan_nativegrayscale_CameraPreview */

#ifndef _Included_io_github_melvincabatuan_nativegrayscale_CameraPreview
#define _Included_io_github_melvincabatuan_nativegrayscale_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_melvincabatuan_nativegrayscale_CameraPreview
 * Method:    ImageProcessing
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_melvincabatuan_nativegrayscale_CameraPreview_ImageProcessing
  (JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
